sudo: false
language: python
cache: pip
matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py27-dj111
    python: 2.7
  - env: TOX_ENV=py34-dj111
    python: 3.4
  - env: TOX_ENV=pypy-dj111
    python: pypy
  - env: TOX_ENV=py35-dj111
    python: 3.5
  - env: TOX_ENV=py36-dj111
    python: 3.6
  - env: TOX_ENV=pypy3-dj111
    python: pypy3
  - env: TOX_ENV=py34-dj20
    python: 3.4
  - env: TOX_ENV=py35-dj20
    python: 3.5
  - env: TOX_ENV=py36-dj20
    python: 3.6
  - env: TOX_ENV=pypy3-dj20
    python: pypy3
  - env: TOX_ENV=py35-djmaster
    python: 3.5
  - env: TOX_ENV=py36-djmaster
    python: 3.6
  - env: TOX_ENV=flake8
  - env: TOX_ENV=isort
  - env: TOX_ENV=readme
  - env: TOX_ENV=check-manifest
  allow_failures:
  - env: TOX_ENV=py35-djmaster
  - env: TOX_ENV=py36-djmaster
  - env: TOX_ENV=py27-dj111
  - env: TOX_ENV=pypy-dj111
addons:
  apt:
    sources:
    - travis-ci/sqlite3
    packages:
    - sqlite3
install:
- pip install -U pip setuptools tox wheel
before_script:
- sqlite3 -version
script:
- tox -e "${TOX_ENV}"
deploy:
  provider: pypi
  user: uncovertruth
  password:
    secure: vm63jxiupnzZI1A9UwiE8JOJ02/7u8sIHUdx0K4Nb9teqZew+uk4DaSSY6MXtjFtatnBocBG/9xc7Ej90suFfQzx5ouYguWvhMDnBivzSvFQ+L68PlgNQ2od09r7NidCOKMkgBDjM0wPnSjzAfaPQatc3PCHcA04BOH10+KPZdDDNQtvjiqRPcFuIZiet0yA5ZECDy4vYeZInXREikbFneKW4NH35eigtZbxxXPX1QBTP9eWPbEM9Hjy+q79/njXHSkyTvdeCjfBHj2Uqul78FVwxdZI37Q4Bl7dgnJ96ccqmHVPEkdhW2wpIcu04hvF1Yo6xVmcx6xsSK77lNh2apLJh5eaYv0jA107z0XszamUZyhMrIIXhrMeXOFOBvsc6oT+VvV7AIfJTLulmsRT49fwAPxzyjobGwqTN0vEJAtfux07WptR2e1IQvOGIzl2JMBckEB+37ecB5H50fW0F9MjxzsE99nEkM0QkKRe64UEZ45Dtgltzdg91JdDzhJMD7qJAfaUpLsBc2dXeoi9Is/QgpPJ15vA7JWmMOuV0eT0gaIHuaRHGd5SHT75jAmu3v5ygulXVIesytasoFFfICWDXP4YsPro+PNmyTd8QW+tAJkigSFt85E5fYhdTToZ4jDMGFC2+ryoxUkk84XX1Ax3Fu22QRip8XjWRRz72Uc=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: uncovertruth/django-horizon
    condition: "$TOX_ENV = py36-dj20"
notifications:
  email: false
  slack:
    secure: HPa3L23uNVcVnXsNtkMkIuhOEOLTqvSbcXPy3ScjHEuZrRqKhHaX6DPx2/6PXR6azyKmywoqcVxDNfAiK5ditlvefxKyp8a1Csduwd4uGEqxAgxM72F/Qjfdb+QXCVp2M6ypjy8H9GSZ8pR888Bea1Vid49c8z1JEr3FbTw/acfY4WGeZTrbD2ZEsVYSEKJR/vS7/YxEY3jO4qxRoGul056LhZvabKACM0TseQkPIDLbY+/f/21LOz1d6TRdukRV9PdOp2lN4wJSloNja3j1x3Ox/auX2U1wAekH33HWyMi3au6X0zdLrEoNhCWdkfRy22qr/JSqeq+qo8xo4bzPrrMuUYzSBtMSp16BWQj47NSJAOhyIlMvtKbRgFdHuu+4XxRpGcmg+MjFdtyzOOjXldMr95adI9+RKzWLQUvBtxJFptDW48yf2t+VIP1WnNfHHoIjj1rROyGTGTE36FrbjAi3V5oRWYBkpKMEmlcVmN/1DKoQ8GECyDKlw0R84xYWUau/LpM20THFzEnPgqUY/DG7a9aqYR/Szo0FY4NuHcW3jzBKeH0xQEOps2OeVVfr7CHcq9NK1AAFYOMeEi5LR6yMfBpbzfVKSRU5EgvmcH8Sr5pBP77UMxiersCEwK3GvwLGrioV4KY598GTGti4tcRaoc1PU+7+EmeFdsGPi4w=
